### ISSUE TITLE
Text formatting not rendering correctly on website

### ISSUE THREAD

**Issue by rachellombardi** [OSGConnect/connectbook#117]
On the "Is the Open Science Pool for You?" page (https://support.opensciencegrid.org/support/solutions/articles/5000632058), the asterisks under the table are not rendering correctly not the website. The text looks fine when rendered on GitHub, but on the website, the asterisks are italicizing "or checkpointable" and making it so that there is only one asterisk (instead of two) in front of " *per job ".

 Thus, the number of asterisks in the table are not consistent with those defined below it.

**Comment by ChristinaLK** [comment]
Addressed.
