### ISSUE TITLE
dHTC vs. DHTC vs. no abbreviation

### ISSUE THREAD

**Issue by rachellombardi** [OSGConnect/connectbook#118]
The phrase "distributed high throughput computing" is abbreviated inconsistency throughout some OSG resources. 

- dHTC is used on several of the main OSG welcome pages: [Welcome Page](https://opensciencegrid.org), [Open Science Pool](https://opensciencegrid.org; https://opensciencegrid.org/about/open_science_pool/), [Ideal Computing](https://opensciencegrid.org/about/computation-ideal-for-OSPool/)

- DHTC is used on [Running OSG jobs on XSEDE](https://support.opensciencegrid.org/support/solutions/articles/12000056361--running-osg-jobs-on-xsede

-Elsewhere in documentation (e.g. [Using software in OSG](https://support.opensciencegrid.org/support/solutions/articles/5000634395-using-software-in-osg-connect)) the phrase is not abbreviated. 

Therefore,
(1) Should the abbreviation be dHTC or DHTC?
(2) Is it helpful to the reader to have this term abbreviated only in the Introductory OSG information but not elsewhere in the documentation, or is it just another term to try to remember (e.g. in the introductory material, new users are also introduced to "OSG", "OSPool", "OSG Connect", "OSG Consortium", "PAth", etc)? 

Once I get feedback, I am happy to make the necessary pull requests.

**Comment by rachellombardi** [comment]
The main [OSG](https://opensciencegrid.org) page has the PAth program described using "Distributed" --> it should be a lower case D to be consistent with the text (i.e. "distributed HTC") under the "The OSG Consortium". 

I would make this change via pull request, but I cannot find the corresponding GitHub page.

**Comment by ChristinaLK** [comment]
Moved to RESFACIL-44
