### ISSUE TITLE
Remove escape in GPU guide 

### ISSUE THREAD

**Issue by rachellombardi** [OSGConnect/connectbook#133]
https://chtc.cs.wisc.edu/uw-research-computing/gpu-jobs

Is the \ necessary in this line of code? 
[alice@submit]$ condor_status -compact -constraint 'TotalGpus > 0' \
			-af Machine TotalGpus CUDADeviceName CUDACapability

**Comment by ChristinaLK** [comment]
Moved to CHTC github repo
