### ISSUE TITLE
Module pages

### ISSUE THREAD

**Issue by CarrieBrown** [OSGConnect/connectbook#22]
Check to ensure information on loading and using modules is up to date and consolidated (remove out of date pages).

**Comment by ChristinaLK** [comment]
**OUT OF DATE**

- tutorials/tutorial-namd/README.md = 5000634378
- tutorials/tutorial-stash-namd/README.md = 5000639799
- tutorials/tutorial-pegasus-namd/README.md = 5000639790
- 
- tutorials/tutorial-gromacs/README.md = 5000645191
- 
- tutorials/tutorial-cp2k/README.md = 5000639784
- 
- tutorials/tutorial-matlab-RandomMatrix/README.md = 5000660781
- tutorials/tutorial-matlab-ResonanceODE/README.md = 5000660782
- tutorials/tutorial-matlab-SimulatedAnnealing/README.md = 5000660783
- 
- tutorials/tutorial-python-virtualenv/README.md = 12000021525
- tutorials/tutorial-VinaAutodock/README.md = 5000634379
- tutorials/tutorial-pegasus-vina/README.md = 5000639792
- 
- tutorials/tutorial-blast/README.md = 5000634380
- tutorials/tutorial-pegasus-blast/README.md = 5000645221
- tutorials/tutorial-stashcache-blast/README.md = 12000003724
- 
- tutorials/tutorial-makeflow-quickstart/README.md = 12000007096
- tutorials/tutorial-makeflow-gromacs/README.md = 12000007775
- tutorials/tutorial-dagman-namd/README.md = 5000634386, 5000639932
- 
- tutorials/tutorial-fsurf/README.md = 12000003417
- tutorials/tutorial-fsurf/README-remote.md = 12000007776

**Comment by ChristinaLK** [comment]
**SALVAGEABLE**

- tutorials/tutorial-R/README.md = 5000674219
- tutorials/tutorial-python-virtualenv/README.md = 12000021525
- tutorials/tutorial-R-addlibSNA/README.md = 5000674218
- tutorials/tutorial-ScalingUp-R/README.md = 5000674221
- 
- tutorials/tutorial-pegasus/README.md = 5000639789 ??
- tutorials/tutorial-swift/README.md = 5000639800

**Comment by ChristinaLK** [comment]
OUT OF DATE = would need to install new module

SALVAGEABLE = mostly R / Python where we just need to change the module name.

**Comment by ChristinaLK** [comment]
Currently coordinating via a Google Sheet.
