### ISSUE TITLE
advice for instruction set compiles

### ISSUE THREAD

**Issue by ChristinaLK** [OSGConnect/connectbook#68]
Create a page that provides guidance on how to handle software compiled w/ specific operation instructions. 
- provide sample requirements to require certain instruction sets, with a note about availability of each
- talk about changing how code is compiled (what flags to look out for, etc.)

Also add a note to the general software guide that links to this new page.

**Comment by lmichael107** [comment]
Why not just add this to our (since-added) guide on compiling from source?

**Comment by ChristinaLK** [comment]
Moved to JIRA RESFACIL-53
